spring.application.name=coding-agent
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=qwen3.5:4b
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash